import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Users</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col min-h-screen">
				<main className="flex flex-col justify-around items-center mt-3 text-white">
					Users
				</main>
			</div>
		</>
	);
}
